# Configuration for Camera Movement Estimation

# ----------------------------------------------
# General settings
device: "cuda:0"  # "cpu" or "cuda:0"

# ----------------------------------------------
# Preprocessing settings
input_video:
  frame_rate_reduction: 5  # Reduce frame rate by this factor
  resize_factor: 0.2       # Resize factor for input video

# ----------------------------------------------
#  Trackers
tracker:
  model_path: "assets/models/trackers/YOLOv5/best.pt"
  tracker_type: "YOLOv5"  # "YOLOv5" or "DeepSORT"
  stub_path: "stubs/trackers/YOLOv5/{video_name}_track_stubs.pkl"
# ----------------------------------------------
# Camera movement estimation settings
camera_movement:
  minimum_distance: 5
  features:
    max_corners: 100
    quality_level: 0.3
    min_distance: 3
    block_size: 7
    mask:
      left_border: 20
      right_border: [900, 1050]
  lk_params:
    win_size: [15, 15]
    max_level: 2
    max_count: 10
    epsilon: 0.03
  read_from_stub: false
  stub_path: null
  save_visualization: true
  estimation_method: "sift"    # or "optical_flow"
  smoothing:
    enabled: true
    window_size: 5

# ----------------------------------------------
# Pitch line detection settings
pitch_lines_detection:
  model: "no_bells_just_whistles"  # "basic" or "no_bells_just_whistles"
  no_bells_just_whistles:
    config_kp_path: "config/models/hrnetv2_w48.yaml"
    config_lines_path: "config/models/hrnetv2_w48_l.yaml"
    model_kp_path: "assets/models/pitch/SV_FT_WC14_kp"
    model_lines_path: "assets/models/pitch/SV_FT_WC14_lines"
    kp_threshold: 0.1486
    lines_threshold: 0.3880
    input_shape: [224, 224, 3]
    output_shape: [224, 224, 1]
    threshold: 0.5
  basic:
    detection_method: "combined"   # Options: "canny", "adaptive", "sobel", "combined"
    canny_low: 50
    canny_high: 150
    hough_threshold: 50
    min_lines_length: 100
    max_lines_gap: 10
    binary_threshold: 200
    adaptive_block_size: 11
    adaptive_C: 2